export const ICON_NAME_MAP: Record<string, string> = {
  wallet: 'wallet-outline',
  bank: 'business-outline',
  landmark: 'business-outline',
  'credit-card': 'card-outline',
  smartphone: 'phone-portrait-outline',
  'dollar-sign': 'cash-outline',
  coffee: 'cafe-outline',
  'shopping-cart': 'cart-outline',
  utensils: 'restaurant-outline',
  truck: 'car-outline',
  droplet: 'water-outline',
  navigation: 'navigate-outline',
  gift: 'gift-outline',
  briefcase: 'briefcase-outline',
  bag: 'bag-outline',
  star: 'star-outline',
  desktop: 'desktop-outline',
  motorcycle: 'car-sport-outline',
  bicycle: 'bicycle-outline',
  land: 'map-outline',
  tablet: 'tablet-portrait-outline',
  tools: 'construct-outline',
  printer: 'print-outline',
  home: 'home-outline',
  electricity: 'flash-outline',
  internet: 'wifi-outline',
  'phone-call': 'call-outline',
  gas: 'flame-outline',
  education: 'school-outline',
  health: 'medkit-outline',
  transport: 'bus-outline',
  tv: 'tv-outline',
  clothing: 'shirt-outline',
  insurance: 'shield-checkmark-outline',
  repair: 'hammer-outline',
  furniture: 'bed-outline',
  camera: 'camera-outline',
  watch: 'watch-outline',
  grocery: 'basket-outline',
  pet: 'paw-outline',
  'gold-bar': 'diamond-outline',
  gem: 'diamond-outline',
  banknote: 'cash-outline',
  charity: 'hand-left-outline',
};

export function resolveIconName(icon: string, fallback = 'ellipse'): string {
  if (!icon) return fallback;
  return ICON_NAME_MAP[icon] || icon;
}
